# Generated by Django 6.0.7 on 2026-08-07 11:34

import django.db.models.deletion
import modules.wallet.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallets',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_wallet_balance_greater_than_zero')],
            },
        ),
        migrations.CreateModel(
            name='TransactionIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_keys', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_transaction_idempotency_key',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer'), ('subscription', 'Subscription')], max_length=15)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=15)),
                ('balance_before', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.transactionidempotencykey')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='transactionidempotencykey',
            index=models.Index(fields=['wallet'], name='wallet_index'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-id'], name='wallet_tran_wallet__d405e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_transaction_amount_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='wallet_transaction_balance_after_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_before__gte', 0)), name='wallet_transaction_balance_before_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', modules.wallet.enums.TransactionCategory)), name='wallet_transaction_category_only_values'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', modules.wallet.enums.TransactionType)), name='wallet_transaction_type_only_values'),
        ),
    ]
