# Generated by Django 6.0.7 on 2026-07-31 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transactionidempotencykey_transaction_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.transactionidempotencykey'),
        ),
        migrations.AlterField(
            model_name='transactionidempotencykey',
            name='idempotency_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
