# Generated by Django 6.0.7 on 2026-08-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_wallet_balance_amount_gte_zero'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionidempotencykey',
            index=models.Index(fields=['wallet'], name='wallet_index'),
        ),
        migrations.AddIndex(
            model_name='transactionidempotencykey',
            index=models.Index(fields=['idempotency_key'], name='idempotency_key_index'),
        ),
    ]
