# Generated by Django 6.0.7 on 2026-08-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transactionidempotencykey_wallet_index_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionidempotencykey',
            name='idempotency_key_index',
        ),
    ]
