services:
  db:
    image: mysql:8.4
    container_name: gym_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "127.0.0.1:3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p\"$$MYSQL_ROOT_PASSWORD\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:5
    container_name: gym_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    ports:
      - "127.0.0.1:8088:80"
    depends_on:
      db:
        condition: service_healthy
  redis:
    image: redis:alpine3.23
    container_name: gym_redis
    restart: unless-stopped
    volumes:
      - gym-redis:/data
    ports:
      - '${FORWARD_REDIS_PORT:-6378}:6379'
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        retries: 3
        timeout: 5s
volumes:
  mysql_data:
  gym-redis: