# Generated by Django 6.0.7 on 2026-08-06 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceproducts',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationproduct'),
        ),
        migrations.AddField(
            model_name='invoicesubscription',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='invoicesubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationsubscription'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='invoice_invoice_amount_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='invoiceproducts',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='invoice_invoiceproducts_price_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='invoiceproducts',
            constraint=models.CheckConstraint(condition=models.Q(('count__gt', 0)), name='invoice_invoiceproducts_count_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='invoicesubscription',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='invoice_invoicesubscription_price_greater_than_zero'),
        ),
    ]
