# Generated by Django 6.0.7 on 2026-07-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.wallet'),
        ),
    ]
