# Generated by Django 6.0.7 on 2026-08-06 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organization.organization'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name',), name='name_unique'),
        ),
        migrations.AddConstraint(
            model_name='organizationproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='organization_organizationproduct_price_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='organizationproduct',
            constraint=models.UniqueConstraint(fields=('name',), name='organization_organizationproduct_name_should_be_unique'),
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='organization_organizationsubscription_price_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.UniqueConstraint(fields=('name',), name='organization_organizationsubscription_name_should_be_unique'),
        ),
    ]
