# Generated by Django 6.0.7 on 2026-08-06 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Hourly', 'Hourly')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished')], default='Active', max_length=13)),
                ('available_usage', models.IntegerField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='invoice.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'organization_id', 'status'], name='subscriptio_user_id_677982_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expiration_date__gt', models.F('start_date'))), name='start_date_less_than_expiration_date'), models.CheckConstraint(condition=models.Q(('available_usage__gte', 0)), name='available_usage_should_not_be_ngeative')],
            },
        ),
    ]
