# Generated by Django 6.0.7 on 2026-08-06 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Hourly', 'Hourly')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished')], default='Active', max_length=13)),
                ('available_usage', models.IntegerField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='invoice.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='organization.organization')),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
    ]
