# Generated by Django 6.0.7 on 2026-08-06 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user_id', 'organization_id', 'status'], name='user_subscr_user_id_b2d793_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('expiration_date__gt', models.F('start_date'))), name='start_date_less_than_expiration_date'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('available_usage__gte', 0)), name='available_usage_should_not_be_ngeative'),
        ),
    ]
